### ISSUE TITLE
Invalid parsing/validation

### ISSUE THREAD

**Issue by qrilka** [ocramz/xeno#10]
As I understand the idea of this lib is to follow more or less `hexml` so I was using it as a base for comparison.
Some found inconsistencies:

1.  Not closed tags accepted by `validate`
```
λ> isRight $ Text.XML.Hexml.parse "<b>"
False
λ> Xeno.SAX.validate "<b>"
True
```
2. Leading whitespace characters don't get accepted by `Xeno.DOM`:
```
λ> isRight $ Xeno.DOM.parse "\n<a></a>"
False
λ> isRight $ Text.XML.Hexml.parse "\n<a></a>"
True
```
3. XML prologue gets accepted by `validate` but not by `Xeno.DOM.parse`
```
λ> isRight $ Text.XML.Hexml.parse "<?xml version=\"1.1\"?>\n<greeting>Hello, world!</greeting>"
True
λ> isRight $ Xeno.DOM.parse "<?xml version=\"1.1\"?>\n<greeting>Hello, world!</greeting>"
False
```

**Comment by dredozubov** [comment]
Makes sense to split into 3 separate issues, I guess.

**Comment by ocramz** [comment]
@qrilka @dredozubov @chrisdone Split this into #14 , #15 and #16 .
