### ISSUE TITLE
Can you release a new version?

### ISSUE THREAD

**Issue by dredozubov** [ocramz/xeno#13]
I'm pretty close to releasing https://github.com/dredozubov/sax-parser which is a monadic sax parser based on xeno. My code depends on a xeno master branch, I would really appreciate releasing a new version of xeno to hackage!

**Comment by dredozubov** [comment]
cc @ocramz

**Comment by ocramz** [comment]
Hi @dredozubov , it's up from now as https://hackage.haskell.org/package/xeno-0.3.3 . However the API didn't change in significant ways since 0.3 so I'm not sure which features you were lacking.

**Comment by dredozubov** [comment]
@ocramz Thank you! I think it was related to the types(or quantity) of sax-handlers in `Xeno.SAX.process`.

**Comment by ocramz** [comment]
@dredozubov Cool : )
