### ISSUE TITLE
`validate` accepts un-paired tags

### ISSUE THREAD

**Issue by ocramz** [ocramz/xeno#14]
```
λ> isRight $ Text.XML.Hexml.parse "<b>"
False
λ> Xeno.SAX.validate "<b>"
True
```

**Comment by chrisdone** [comment]
That's a SAX parser, so it doesn't look at hierarchy, it only validates lexical correctness.

`<b>` is valid, but e.g. `<b` would not validate.

Try the DOM module.

**Comment by qrilka** [comment]
So I guess it's worth a note in haddocks
