### ISSUE TITLE
Leading whitespace characters are not accepted by `Xeno.DOM`

### ISSUE THREAD

**Issue by ocramz** [ocramz/xeno#15]
```
λ> isRight $ Xeno.DOM.parse "\n<a></a>"
False
λ> isRight $ Text.XML.Hexml.parse "\n<a></a>"
True
```

**Comment by qrilka** [comment]
This one also seems to be fixed in #11 - see https://github.com/ocramz/xeno/pull/11/files#diff-9d8af650b97d18f1fafe6aabb2744744R133 but I didn't add a test case for it
