### ISSUE TITLE
update stack.yaml

### ISSUE THREAD

**Issue by ocramz** [ocramz/xeno#29]
I think the format has changed with stack 2 because now travis complains with

```
$ stack $ARGS --no-terminal --install-ghc test --haddock

Could not parse '/home/travis/build/ocramz/xeno/stack.yaml':
Aeson exception:
Error in $.packages[1]: failed to parse field 'packages': expected Text, encountered Object
```

**Comment by qrilka** [comment]
@ocramz I didn't try it out but my suspicion is that the problem is about git package not in `extra-deps` see the proposed fix in https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md#packages
