### ISSUE TITLE
Maintenance hand-over

### ISSUE THREAD

**Issue by ocramz** [ocramz/xeno#31]
As I wrote yesterday : https://www.reddit.com/r/haskell/comments/e4lvcz/xeno_seeking_maintainers/ 

I would like to hand over maintenance of `xeno` to someone who can give it the love it deserves. There are some routine maintenance tasks for which I haven't had the time recently.

@tmcgilchrist volunteered, but I wonder whether other contributors/pro users @qrilka @unhammer have any wishes regarding this.

**Comment by qrilka** [comment]
I don't think that I have anything specific from my side. I'll keep watching the repo and will be glad to provide some additional help if I will be able to.

**Comment by unhammer** [comment]
ditto, great that there is a volunteer so soon :)

**Comment by ocramz** [comment]
@tmcgilchrist it's not possible to transfer the repo to you because you already have a fork of `xeno`. I guess we should merge any outstanding work you might have on your fork into this one and then transfer it.

**Comment by tmcgilchrist** [comment]
I’ve backed up my fork locally and deleted it on github. Should be ok to do
the transfer now.

**Comment by mgajda** [comment]
Migamake would be happy to take it under our wings, since we work on improving it all the time.

**Comment by dmalkr** [comment]
I can maintain xeno. We with @mgajda in Migamake already extensively have used xeno in our projects, already have made some improvements (you can view it in https://gitlab.com/migamake/xeno repository; particularly we speed up SAX / DOM processing at least at ~50%).

So please consider me as maintainer.

**Comment by ocramz** [comment]
@dmalkr @mgajda oh wow that's great! Would you like to merge your fork before handing over?

**Comment by dmalkr** [comment]
> @dmalkr @mgajda oh wow that's great! Would you like to merge your fork before handing over?

PR is ready: https://github.com/ocramz/xeno/pull/35

I've placed all changes in one PR. If you need, I can split into several PRs.

**Comment by mgajda** [comment]
@ocramz Are you waiting for handover? Because I am ready to take over.

**Comment by ocramz** [comment]
Hi @mgajda , sorry for the long delay, I haven't been active in open source in the past few months. I've added you to the maintainer list on Hackage but you should first get rid of your fork of xeno before we can transfer it. I'll be happy to merge any outstanding work you might have there before transferring.

**Comment by chrisdone** [comment]
I just found this thread.

> I can maintain xeno. We with @mgajda in Migamake already extensively have used xeno in our projects, already have made some improvements (you can view it in https://gitlab.com/migamake/xeno repository; particularly we accelerated SAX / DOM processing at least ~50%, added a lot of benchmarks for big XML files (1-20Gb)).
> 
> So please consider me as maintainer.

That's very interesting!

Thanks @mgajda for taking over maintainership.

Also thanks to @ocramz for maintaining since 2017~.

**Comment by mgajda** [comment]
Taken over :-).
