### ISSUE TITLE
"xeno-bench" should be a benchmark

### ISSUE THREAD

**Issue by PaulJohnson** [ocramz/xeno#40]
The "xeno-bench" target in the Cabal file is listed as an executable, but it should be a benchmark.

Amongst other things this means that Stack believes that "bytestring-mmap" is a required dependency, which causes the build to fail on Windows.

**Comment by ocramz** [comment]
Thank you, the fix is on Hackage as of 0.4.2 : https://hackage.haskell.org/package/xeno-0.4.2
