### ISSUE TITLE
Digits in element names

### ISSUE THREAD

**Issue by mcmayer** [ocramz/xeno#6]
Element names containing digits, e.g. something like `<sha1>p9przoiizhx3wz7d46d5erk4wj20j1q</sha1>`, cannot be parsed, although they are legal.
@AlexeyRaga has a fix for this (no pull request). Should this be merged?
**Update**:
The simple way is to slightly change `isNameChar`, but that leads to a too permissive parser, e.g. the illegal `<1ab>...</1ab>` *would* be parsed.

**Comment by ocramz** [comment]
Hi @mcmayer , thank you for filing this issue and sorry for the long delay. What fix do you suggest?
